# Generated by Django 5.2.5 on 2025-09-27 02:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name': 'カテゴリ',
                'verbose_name_plural': 'カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='店舗名')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='住所')),
                ('budget', models.CharField(choices=[('LOW', '〜999円'), ('MED', '1,000〜2,999円'), ('HIGH', '3,000円〜')], default='MED', max_length=4, verbose_name='予算')),
                ('closed_days', models.CharField(blank=True, max_length=10, verbose_name='定休日')),
                ('opening_hours', models.CharField(blank=True, max_length=20, verbose_name='営業時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shops', to='app.category', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
                'indexes': [models.Index(fields=['name'], name='app_shop_name_c04557_idx'), models.Index(fields=['address'], name='app_shop_address_d2124b_idx')],
            },
        ),
    ]
