# Generated by Django 5.2.5 on 2025-11-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shop_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
