# Generated by Django 5.2.5 on 2025-11-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='detail',
        ),
        migrations.AddField(
            model_name='shop',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
