# Generated by Django 5.2.5 on 2025-11-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='price',
            field=models.IntegerField(default=1000, verbose_name='予約料金（円）'),
        ),
    ]
