# Generated by Django 5.2.5 on 2025-11-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_shop_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会社名')),
                ('founded_year', models.IntegerField(verbose_name='創立年')),
                ('description', models.TextField(verbose_name='事業内容')),
                ('headquarters', models.CharField(max_length=200, verbose_name='本社所在地')),
            ],
        ),
    ]
