# Generated by Django 5.2.5 on 2025-11-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_memberprofile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='名前'),
        ),
    ]
