# Generated by Django 5.2.5 on 2025-11-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_memberprofile_is_premium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='stripe_subscription_id',
        ),
    ]
